#!/bin/bash

set -e
set -x

HARNESSES=(node-spa viper)

function main()
{
    if ! command -v splitsh-lite >/dev/null; then
        echo "error: splitsh-lite is needed to be installed first" >&2
        exit 1
    fi

    git checkout -b _build

    build

    set_remote "base" "git@github.com:inviqa/harness-node.git"
    splitsh-lite --prefix="src/_base" --target="publish/harness-node"
    git push -q -f "base" "publish/harness-node:0.2.x"

    for harness in "${HARNESSES[@]}"
    do
        set_remote "$harness" "git@github.com:inviqa/harness-${harness}.git"
        splitsh-lite --prefix="src/${harness}" --target="publish/harness-${harness}"
        git push -q -f "$harness" "publish/harness-${harness}:0.2.x"
    done

    git checkout 0.2.x
    git branch -D _build
}

function set_remote()
{
    local name="$1"
    local path="$2"

    if ! git ls-remote --exit-code "$name" &>/dev/null; then
        git remote add "$name" "$path"
    fi
}

function build()
{
    for harness in "${HARNESSES[@]}"
    do
        rsync -va --ignore-existing "./src/_base/" "./src/$harness"
        git add .
        git commit -m "publish '${harness}' harness"
    done
}

main
