apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resourcePrefix }}viper-gateway
  labels:
    app.service: {{ .Values.resourcePrefix }}viper-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.service: {{ .Values.resourcePrefix }}viper-gateway
  template:
    metadata:
      labels:
        app.service: {{ .Values.app.resourcePrefix }}viper-gateway
    spec:
      containers:
      - name: viper-gateway
        {{- if .Values.gateway.env }}
        env:
        {{- range $key, $value := .Values.gateway.env }}
        {{- $tp := typeOf $value }}
        - name: {{ $key | quote }}
        {{- if eq $tp "string" }}
          value: {{ tpl $value $ | quote }}
        {{- else}}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        {{- end }}
        image: {{ .Values.app.image }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: {{ .Values.gateway.port }}
        resources:
          limits:
            memory: "{{ .Values.gateway.resources.memory }}"
          requests:
            memory: "{{ .Values.gateway.resources.memory }}"
        readinessProbe:
          tcpSocket:
            port: {{ .Values.gateway.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
{{- if .Values.app.image_pull_config }}
      imagePullSecrets:
      - name: {{ .Values.app.resourcePrefix }}image-pull-config
{{- end }}
      restartPolicy: Always
      enableServiceLinks: false
status: {}
