{{ if .Values.gateway.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.gateway.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.gateway.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.service: {{ .Values.app.resourcePrefix }}viper-gateway
{{- if .Values.gateway.ingress.labels }}
{{- toYaml .Values.gateway.ingress.labels | nindent 4 }}
{{- end }}
  name: {{ .Values.app.resourcePrefix }}viper-gateway
spec:
  rules:
  {{- if .Values.gateway.ingress.hosts }}
  {{- range $host := .Values.gateway.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - backend:
              serviceName: {{ $.Values.app.resourcePrefix }}viper-gateway
              servicePort: 80
  {{- end -}}
  {{- end }}
status:
  loadBalancer: {}
{{ end }}
