{{- if .Values.services.nginx.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resourcePrefix }}nginx
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: nginx
    app.service: {{ .Values.resourcePrefix }}nginx
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.service: {{ .Values.resourcePrefix }}nginx
  template:
    metadata:
      labels:
        {{- include "chart.selectors" $ | nindent 8 }}
        app.kubernetes.io/component: nginx
        app.service: {{ .Values.resourcePrefix }}nginx
    spec:
      containers:
      {{- with .Values.services.nginx }}
      - name: nginx
        env:
        {{- range $key, $value := (mergeOverwrite (dict) .environment .environment_dynamic) }}
        {{- $tp := typeOf $value }}
        - name: {{ $key | quote }}
        {{- if eq $tp "string" }}
          value: {{ tpl $value $ | quote }}
        {{- else}}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        {{- if .environment_secrets }}
        envFrom:
          - secretRef:
              name: {{ $.Values.resourcePrefix }}nginx
        {{- end }}
        image: {{ .image }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            memory: {{ .resources.memory }}
          requests:
            memory: {{ .resources.memory }}
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      {{- end }}
{{- if .Values.docker.image_pull_config }}
      imagePullSecrets:
      - name: {{ .Values.resourcePrefix }}image-pull-config
{{- end }}
      restartPolicy: Always
      enableServiceLinks: false
status: {}
{{- end }}
