{{ if and (index .Values.services .Values.ingress.target_service "enabled") (eq .Values.ingress.type "standard") }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
{{- with .Values.ingress.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
{{- end }}
  creationTimestamp: null
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
    app.service: {{ .Values.resourcePrefix }}nginx
  name: {{ .Values.resourcePrefix }}nginx
spec:
  rules:
  - host: {{ index .Values.services "nginx" "environment" "APP_HOST" }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.resourcePrefix }}{{ .Values.ingress.target_service }}
          servicePort: 80
status:
  loadBalancer: {}
{{- end }}
