{{ if and (index .Values.services .Values.ingress.target_service "enabled") (eq .Values.ingress.type "istio") }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.resourcePrefix }}nginx-virtualservice
{{- with .Values.ingress.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
{{- end }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: nginx
    app: {{ .Values.resourcePrefix }}nginx
    app.service: {{ .Values.resourcePrefix }}nginx
spec:
  hosts:
  - {{ index .Values.services "nginx" "environment" "APP_HOST" }}
  gateways:
{{- range $key, $value := .Values.istio.gateways }}
  - {{ tpl $value $ | quote }}
{{- end }}
  http:
  - route:
    - destination:
        host: {{ .Values.resourcePrefix }}nginx
        port:
          number: 80
{{ end }}
