{{- if index .Values.services .Values.ingress.target_service "enabled" -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: nginx
    app.service: {{ .Values.resourcePrefix }}nginx
  name: {{ .Values.resourcePrefix }}nginx
spec:
  ports:
  - name: http-80
    port: 80
    targetPort: 80
  selector:
    app.service: {{ .Values.resourcePrefix }}nginx
status:
  loadBalancer: {}
{{- end }}
