
confd('harness:/'):
  # base templates
  - { src: application/overlay/Jenkinsfile }
  - { src: application/overlay/.dockerignore, dst: workspace:/.dockerignore }
  - { src: application/skeleton/README.md }
  - { src: mutagen.yml, dst: workspace:/mutagen.yml }
  - { src: docker-compose.yml, dst: workspace:/docker-compose.yml }
  - { src: helm/app/values.yaml }
  - { src: helm/app/values-production.yaml }
  - { src: helm/app/values-preview.yaml }
  - { src: helm/app/Chart.yaml }
